-- =====================================================================
-- Jarvis Мастер — схема базы данных для Supabase (PostgreSQL)
-- Как использовать: Supabase → SQL Editor → New query → вставить весь
-- этот текст → Run. Всё создастся автоматически.
-- Имена колонок в camelCase специально совпадают с полями Android-кода.
-- =====================================================================

-- ---------- Таблица: клиенты ----------
create table if not exists public.clients (
    "id" bigint generated by default as identity primary key,
    "name" text not null default '',
    "phone" text not null default '',
    "telegram" text not null default '',
    "note" text not null default '',
    "createdAt" bigint not null default 0
);

-- ---------- Таблица: ремонты ----------
create table if not exists public.repairs (
    "id" bigint generated by default as identity primary key,
    "clientId" bigint null,
    "deviceName" text not null default '',
    "serialNumber" text not null default '',
    "issue" text not null default '',
    "diagnosis" text not null default '',
    "status" text not null default 'NEW',
    "price" double precision not null default 0,
    "partsCost" double precision not null default 0,
    "receivedDate" bigint not null default 0,
    "readyDate" bigint null,
    "issuedDate" bigint null,
    "warrantyDays" integer not null default 30,
    "receivedPayment" double precision not null default 0,
    "note" text not null default '',
    "createdAt" bigint not null default 0
);
create index if not exists idx_repairs_client on public.repairs("clientId");
create index if not exists idx_repairs_status on public.repairs("status");

-- ---------- Таблица: фото техники (привязка к ремонту) ----------
create table if not exists public.repair_photos (
    "id" bigint generated by default as identity primary key,
    "repairId" bigint not null,
    "url" text not null default '',
    "caption" text not null default '',
    "createdAt" bigint not null default 0
);
create index if not exists idx_photos_repair on public.repair_photos("repairId");

-- ---------- Таблица: запчасти ----------
create table if not exists public.parts (
    "id" bigint generated by default as identity primary key,
    "name" text not null default '',
    "category" text not null default 'Дисплей',
    "barcode" text not null default '',
    "quantity" integer not null default 0,
    "minQuantity" integer not null default 1,
    "purchasePrice" double precision not null default 0,
    "sellPrice" double precision not null default 0,
    "location" text not null default '',
    "note" text not null default ''
);

-- ---------- Таблица: связь ремонт ↔ запчасть ----------
create table if not exists public.repair_parts (
    "repairId" bigint not null,
    "partId" bigint not null,
    "quantity" integer not null default 1,
    "priceAtTime" double precision not null default 0,
    primary key ("repairId", "partId")
);

-- ---------- Таблица: финансы (доходы/расходы) ----------
create table if not exists public.transactions (
    "id" bigint generated by default as identity primary key,
    "type" text not null default 'INCOME',
    "category" text not null default 'Ремонт',
    "amount" double precision not null default 0,
    "date" bigint not null default 0,
    "repairId" bigint null,
    "description" text not null default ''
);
create index if not exists idx_tx_date on public.transactions("date");

-- ---------- Настройки безопасности ----------
-- Для мастерской из 1–2 доверенных людей отключаем строгий RLS,
-- чтобы приложение с anon-ключом могло читать и писать.
alter table public.clients disable row level security;
alter table public.repairs disable row level security;
alter table public.repair_photos disable row level security;
alter table public.parts disable row level security;
alter table public.repair_parts disable row level security;
alter table public.transactions disable row level security;

-- Разрешаем анонимному ключу (сервисному) работать с таблицами
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
grant all on all routines in schema public to anon, authenticated;
